apiVersion: apps/v1
kind: Deployment
metadata: 
  labels:
  name: my-deployment2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my2
  template:
    metadata:
      labels:
        app: my2 
    spec:
      containers:
      - name: my2
        image: iomilala/my-app:latest
        ports: 
        - containerPort: 8080 
---
kind: Service
apiVersion: v1
metadata: 
  name: sr-v2-svc
  labels:
    app: my2
spec:
  selector:
    app: my2
  ports: 
  - name: http
    port: 80
    targetPort: 8080