apiVersion: apps/v1
kind: Deployment
metadata: 
  labels:
  name: my-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my  
  template:
    metadata:
      labels:
        app: my 
    spec:
      containers:
      - name: my
        image: iomilala/my-app:latest
        ports: 
        - containerPort: 8080 
---
kind: Service
apiVersion: v1
metadata: 
  name: sr-v1-svc
  labels:
    app: my
spec:
  selector:
    app: my
  ports: 
  - name: http
    port: 80
    targetPort: 8080